export const GET_CITIES = 'GET_CITIES'
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS'
export const GET_CITIES_FAILURE = 'GET_CITIES_FAILURE'

export const GET_CLAIMS = 'GET_CLAIMS'
export const GET_CLAIMS_SUCCESS = 'GET_CLAIMS_SUCCESS'
export const GET_CLAIMS_FAILURE = 'GET_CLAIMS_FAILURE'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'

export const GET_FAQS = 'GET_FAQS'
export const GET_FAQS_SUCCESS = 'GET_FAQS_SUCCESS'
export const GET_FAQS_FAILURE = 'GET_FAQS_FAILURE'

export const GET_TECHNOLOGIES = 'GET_TECHNOLOGIES'
export const GET_TECHNOLOGIES_SUCCESS = 'GET_TECHNOLOGIES_SUCCESS'
export const GET_TECHNOLOGIES_FAILURE = 'GET_TECHNOLOGIES_FAILURE'

export const GET_ALL_IP_FILTERS = 'GET_ALL_IP_FILTERS'
export const GET_ALL_IP_FILTERS_SUCCESS = 'GET_ALL_IP_FILTERS_SUCCESS'
export const GET_ALL_IP_FILTERS_FAILURE = 'GET_ALL_IP_FILTERS_FAILURE'

export const LOGIN = 'LOGIN'
export const SET_SESSION = 'SET_SESSION'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS'
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE'

export const SEND_OTP = 'SEND_OTP'
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS'
export const SEND_OTP_FAILURE = 'SEND_OTP_FAILURE'

export const VALIDATE_OTP = 'VALIDATE_OTP'
export const VALIDATE_OTP_SUCCESS = 'VALIDATE_OTP_SUCCESS'
export const VALIDATE_OTP_FAILURE = 'VALIDATE_OTP_FAILURE'

export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE'

export const UPDATE_IMAGE = 'UPDATE_IMAGE'
export const UPDATE_IMAGE_FAILURE = 'UPDATE_IMAGE_FAILURE'

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE'

export const ADD_CASE = 'ADD_CASE'
export const ADD_CASE_SUCCESS = 'ADD_CASE_SUCCESS'
export const ADD_CASE_FAILURE = 'ADD_CASE_FAILURE'

export const USER_CASE = 'USER_CASE'
export const USER_CASE_SUCCESS = 'USER_CASE_SUCCESS'
export const USER_CASE_FAILURE = 'USER_CASE_FAILURE'

export const PAYMENT = 'PAYMENT'
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS'
export const PAYMENT_FAILURE = 'PAYMENT_FAILURE'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE'

export const VALIDATE_RESET = 'VALIDATE_RESET'
export const VALIDATE_RESET_SUCCESS = 'VALIDATE_RESET_SUCCESS'
export const VALIDATE_RESET_FAILURE = 'VALIDATE_RESET_FAILURE'

export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE'

export const GET_ALL_GENERIC_DATA = 'GET_ALL_GENERIC_DATA'

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS'
export const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE'
