export const END_POINTS = {
 getCities: 'City/GetAll',
 getTechnology: 'IpFilter/GetAllTechnology',
 getAllIpFilters: 'IpFilter/GetAll',
 userLogin: 'Account/Login',
 sendOtp: 'Account/SendUserOtp',
 validateOtp: 'Account/AuthenticateUserOTP',
 refreshToken: 'Account/RefreshToken',
 userRegister: 'Account/Register',
 getProfile: 'Account/GetById',
 profileUpdate: 'Account/Update',
 updateImage: 'ProfilePicture/UploadProfileImage',
 changePassword: 'Account/ChangePassword',
 getCategories: 'IpFilter/GetAllCategory',
 getClaims: 'Claim/GetAll',
 getFaqs: 'FAQ/GetAll',
 addCase: 'Case/Add',
 getIdCase: 'Case/GetAllUserCases',
 payment: 'Stripe/Charge',
 forgetPassword: 'Account/ForgotPassword',
 validateReset: 'Account/ValidateResetToken',
 resetPassword: 'Account/ResetPassword',
 getNotifications: '/Notification/GetAll'
}